// <auto-generated />
using System;
using FeedbackService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackService.Migrations
{
    [DbContext(typeof(DBApplicationContext))]
    [Migration("20221129112237_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeedbackService.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryId = 1,
                            Message = "Det var godt nok noget dårlig mad mand!!!",
                            Rating = 1,
                            RestaurantId = 1,
                            ReviewDate = new DateTime(2022, 11, 29, 12, 22, 37, 180, DateTimeKind.Local).AddTicks(717),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeliveryId = 1,
                            Message = "Det var godt nok noget lækker mad mand!!!",
                            Rating = 5,
                            RestaurantId = 1,
                            ReviewDate = new DateTime(2022, 11, 29, 12, 22, 37, 180, DateTimeKind.Local).AddTicks(757),
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
